apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-app
spec:
  containers:
    - name: configmap-vol-app
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: volume-map-config
        mountPath: /etc/config/configMap
      - name: secret-store
        mountPath: /etc/config/secret
  volumes:
    # specifying set volumes at the Pod level, then mount them into containers inside the Pod
    - name: volume-map-config
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: config
    - name: volume-map-secret
      secret:
        secretName: secret-store